laszlojakab/homeassistant-dijnet

custom_components/dijnet/dijnet_session.py
custom_components/dijnet/manifest.json
custom_components/dijnet/sensor.py

This PR removes requests package dependency and make all http calls with aiohttp in async way.
Fixes #11

feat: remove requests dependency, use aiohttp

---

custom_components/dijnet/manifest.json

This PR creates release v0.3.0-beta.

release: bump version to v0.3.0-beta

---

custom_components/dijnet/dijnet_session.py

This PR fixes `ROOT_URL` value.

fix: change ROOT_URL

---

README.md
custom_components/dijnet/__init__.py
custom_components/dijnet/config_flow.py
custom_components/dijnet/const.py
custom_components/dijnet/controller.py
custom_components/dijnet/sensor.py
custom_components/dijnet/strings.json
custom_components/dijnet/translations/en.json
custom_components/dijnet/translations/hu.json

This PR adds support for UI based configuration.

feat: add support for UI configuration

---

custom_components/dijnet/manifest.json

This PR creates v0.4.0-beta release.

release: bump version to v0.4.0-beta

---

custom_components/dijnet/config_flow.py
custom_components/dijnet/dijnet_session.py
custom_components/dijnet/strings.json
custom_components/dijnet/translations/en.json
custom_components/dijnet/translations/hu.json

This PR modifies the config and the options flow to validate the username and password

feat: validate username and password

---

custom_components/dijnet/manifest.json

This PR creates release v0,4.3-beta.

release: bump version to v0.4.3-beta

---

custom_components/dijnet/controller.py
custom_components/dijnet/sensor.py

This PR introduceses InvoiceIssuer class.

refactor: introduce InvoiceIssuer class

---

custom_components/dijnet/controller.py
custom_components/dijnet/dijnet_session.py
custom_components/dijnet/sensor.py

This PR refactors DijnetController:
- `DijnetController.get_paid_invoices`: returns paid invoices found at Dijnet website. This will be used for further development.
- `DijnetController.get_unpaid_invoices`: returns unpaid invoices found at Dijnet website.
- `DijnetController` saves the downloaded paid invoices data in file system and reloads on start to reduce number of requests after restarting HA.
- Docstrings added to `DijnetController`

feat: refactor DijnetController, add registry, add Invoice, PaidInvoice classes

---

custom_components/dijnet/controller.py
custom_components/dijnet/dijnet_session.py
custom_components/dijnet/sensor.py

This PR refactors sensors. Old sensor types removed. This is a breaking change!

feat: refactor sensors

---

.github/workflows/validate.yml
hacs.json

This PR adds HACS validation github worflow.

feat: add HACS validate workflow

---

.github/scripts/update_hacs_manifest.py
.github/workflows/release.yml
hacs.json

This PR adds release github workflow and changes the releases to zip_release in hacs.json.

feat: add release github workflow

---

LICENSE

This PR adds MIT license to the project.

feat: add LICENSE file

---

README.md

This PR adds shields to the README.md file.

feat: add sheilds to readme.md

---

README.md

This PR fixes the license shield image in readme.md.

fix: fix license shield in README.md

---

README.md

This PR modifies the shield of license to use dynamic in README.md

fix: change license to dynamic in README.md

---

custom_components/dijnet/controller.py

This PR modifies the function which determines the state of an invoice. Invoice will be:
- paid
- if state column contains 'Rendezett'
- or if state column contains 'Fizetve'
- unpaid
- if state column contains 'Rendezetlen'
- or if state column contains 'Csoportos beszedés' and payment deadline is not reached

fix: handle more cases in invoice state column

---

custom_components/dijnet/controller.py

This PR fixes the calculation of deadline in case of encashment.

fix: encashment deadline calculation

---

custom_components/dijnet/manifest.json

This PR creates release 0.5.1-beta3

feat: release 0.5.1-beta3

---

custom_components/dijnet/controller.py

This PR sets the paid_at value to the deadline if paid_at value not provided on Dijnet website but the state of the invoice is paid.

feat: set paid_at to deadline if paid_at not provided

---

README.md

This PR updates the usage section of README.MD, and adds features and debugging section to it.

feat: update README.MD

---

custom_components/dijnet/manifest.json

This PR creates release 0.5.2-beta.

feat: create release 0.5.2-beta

---

README.md

This PR adds integration usage badge to `readme.md`.

feat: add integration usage to readme.md

---

custom_components/dijnet/controller.py

This PR add support for handling `Beszedés alatt` state.

feat: handle under collecting state

---

custom_components/dijnet/manifest.json

This PR creates release 0.5.3-beta.

feat: create release 0.5.3-beta

---

README.md
custom_components/dijnet/controller.py
custom_components/dijnet/manifest.json

This PR merges the develop to master.

merge: develop to master

---

custom_components/dijnet/manifest.json

This PR creates release 0.5.4-beta.

feat: create release 0.5.4-beta

---

custom_components/dijnet/controller.py
custom_components/dijnet/manifest.json

This PR creates release 0.5.4-beta.

feat: release 0.5.4-beta

---

custom_components/dijnet/controller.py

This PR adds support for  `Mobiltelefonra küldve` state.
References #52

fix: add support for `Mobiltelefonra küldve`

---

custom_components/dijnet/controller.py
custom_components/dijnet/manifest.json

feat: create release 0.5.5

---

custom_components/dijnet/controller.py

This PR adds support for 'Internetbanknak átadva' state.

feat: add support for 'Intenetbanknak átadva'

---

custom_components/dijnet/controller.py
custom_components/dijnet/manifest.json
hacs.json

This PR creates release 0.5.6.

feat: create release 0.5.6

---

custom_components/dijnet/controller.py
custom_components/dijnet/dijnet_session.py

This PR modifies the integration to be able to parse data from the Dijnet site after the modifications introduced at 2022.11.18.

fix: modify parsing according to 2022 11 18

---

custom_components/dijnet/manifest.json
custom_components/dijnet/sensor.py

This PR creates release 0.6.1.

feat: create release 0.6.1

---

custom_components/dijnet/controller.py

This PR fixes issue caused by changes in invoice download page structure.

fix: update css selector for invoice downloading

---

custom_components/dijnet/manifest.json

This PR prepares release v0.6.2.

build: bump version to 0.6.2

---

custom_components/dijnet/controller.py
custom_components/dijnet/manifest.json

This PR creates release 0.6.2.

feat: create release 0.6.2

---

custom_components/dijnet/controller.py
custom_components/dijnet/dijnet_session.py

This PR adds `vfw_token` to search query.

feat: add vfw_token to search query

---

custom_components/dijnet/manifest.json

This PR prepares release `0.6.3`.

 build: bump version to 0.6.3

---

custom_components/dijnet/controller.py
custom_components/dijnet/dijnet_session.py
custom_components/dijnet/manifest.json

This PR creates release `0.6.3`.

feat: create release 0.6.3

---

custom_components/dijnet/controller.py

This PR modifies the code to use proper encoding when processing downloaded html pages.

fix: re-encode responses to UTF-8

---

custom_components/dijnet/manifest.json

This PR prepares release 0.6.4

build: bump version to 0.6.4

---

custom_components/dijnet/controller.py
custom_components/dijnet/manifest.json

This PR creates release `0.6.4`.

feat: create release 0.6.4

---

custom_components/dijnet/__init__.py
custom_components/dijnet/controller.py
custom_components/dijnet/manifest.json
custom_components/dijnet/sensor.py

This PR resolves deprecation warnings.
References #86, #87

feat: solve home assistant warnings

---

.github/scripts/__init__.py
.github/scripts/update_hacs_manifest.py
.github/workflows/ci.yml
Pipfile
Pipfile.lock
custom_components/dijnet/__init__.py
custom_components/dijnet/config_flow.py
custom_components/dijnet/const.py
custom_components/dijnet/controller.py
custom_components/dijnet/dijnet_session.py
custom_components/dijnet/manifest.json
custom_components/dijnet/sensor.py
pyproject.toml

This PR creates release `0.6.5`.

feat: create release 0.6.5
